name: Scrapear y Actualizar Datos

on:
  schedule:
    - cron: '0 23 * * *' # Ejecutar todos los días a las 21:00 Argentina (UTC-3)

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      NOMBRE_ARCHIVO_CSV: datos_scrape_argenprop.csv # Nombre del archivo CSV

    steps:
    - name: Checkout del Código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Instalar Dependencias
      run: pip install numpy pandas requests datetime beautifulsoup4 html5lib

    - name: Ejecutar Scraper
      run: python ejecutar_scrape_argenprop.py

    - name: Verificar si el archivo CSV ha cambiado
      id: chequear-diff-csv
      run: |
        if git diff --quiet ${{ env.NOMBRE_ARCHIVO_CSV }}; then
          echo "::set-output name=csv_fue_modificado::false"
        else
          echo "::set-output name=csv_fue_modificado::true"
        fi

    - name: Obtener la fecha actual
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Actualizar CSV en el Repositorio
      if: steps.chequear-diff-csv.outputs.csv_fue_modificado == 'true'
      run: |
        git config --local user.email "57342159+LeoArtaza@users.noreply.github.com"
        git config --local user.name "LeoArtaza"
        git add ${{ env.NOMBRE_ARCHIVO_CSV }}
        git commit -m "Actualizar datos a fecha ${{ steps.date.outputs.date }}"
        git push